export { default as ThanhCong } from '../alert/ThanhCong/ThanhCong'
export { default as XacNhanSua } from '../alert/XacNhanSua/XacNhanSua'
export { default as SuaThongTin } from '../alert/SuaThongTin/SuaThongTin'
export {default as Delete} from './Delete/Delete'
export {default as ThongBao} from './ThongBao/ThongBao'